//  from emotions.html
use crate::pet::emotions::{EmotionColor, EmotionSpec};

pub fn all_emotions() -> Vec<EmotionSpec> {
    vec![
        EmotionSpec {
            key: "rested".to_string(),
            name: "rested".to_string(),
            color: EmotionColor::Green,
            ms: 900,
            frames: vec![
                "  ╭───╮\n ( ᵔ ᴥ ᵔ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔ ᴥ ᵔ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔ ᴥ ᵔ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔ ᴥ ᵔ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔ ᴥ ᵔ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔ ᴥ ᵔ)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "tired".to_string(),
            name: "tired".to_string(),
            color: EmotionColor::Amber,
            ms: 1800,
            frames: vec![
                "  ╭───╮\n ( -ᴥ- )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ- )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ- )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ-〃)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ-〃)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ- )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "exhausted".to_string(),
            name: "exhausted".to_string(),
            color: EmotionColor::Coral,
            ms: 2400,
            frames: vec![
                "  ╭───╮\n ( x ᴥ x)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( x ᴥ x)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( x ᴥ x)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( x ᴥ x)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( x ᴥ x)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( x ᴥ x)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( _ ᴥ _)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "drowsy".to_string(),
            name: "drowsy".to_string(),
            color: EmotionColor::Amber,
            ms: 1200,
            frames: vec![
                "  ╭───╮\n ( -ᴥ-  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ-〃)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ-〃)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ˘ᴥ˘ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ-  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ-  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ-〃)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( _ ᴥ _)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "wired".to_string(),
            name: "wired".to_string(),
            color: EmotionColor::Coral,
            ms: 220,
            frames: vec![
                "  ╭───╮\n (ò ᴥ ó)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ó ᴥ ò)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ò ᴥ ó)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ó ᴥ ò)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ó ᴥ ó)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ò ᴥ ò)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ò ᴥ ó)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "groggy".to_string(),
            name: "groggy".to_string(),
            color: EmotionColor::Amber,
            ms: 1100,
            frames: vec![
                "  ╭───╮\n ( _ ᴥ _)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( _ ᴥ _)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ˘ᴥ_ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ˘ᴥ˘ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ˘ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ- )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ˘ᴥ- )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ˘ᴥ˘ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "focused".to_string(),
            name: "focused".to_string(),
            color: EmotionColor::Sky,
            ms: 2200,
            frames: vec![
                "  ╭───╮\n (・ᴥ・ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (・ᴥ・ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (・ᴥ・ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (・ᴥ・ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (・ᴥ・ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (⊙ ᴥ ⊙)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (・ᴥ・ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "flow".to_string(),
            name: "deep in flow".to_string(),
            color: EmotionColor::Sky,
            ms: 3000,
            frames: vec![
                "  ╭───╮\n (⊙ ᴥ ⊙)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (⊙ ᴥ ⊙)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (⊙ ᴥ ⊙)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (⊙ ᴥ ⊙)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ★ᴥ★ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (⊙ ᴥ ⊙)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "distracted".to_string(),
            name: "distracted".to_string(),
            color: EmotionColor::Amber,
            ms: 300,
            frames: vec![
                "  ╭───╮\n (¿ ᴥ ¿)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ ¿ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (¿ ᴥ  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (¿ ᴥ ¿)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ   )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (¿ ᴥ ¿)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (  ᴥ ¿)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (¿ ᴥ ¿)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "blocked".to_string(),
            name: "blocked".to_string(),
            color: EmotionColor::Neutral,
            ms: 3500,
            frames: vec![
                "  ╭───╮\n (− ᴥ −)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (− ᴥ −)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (− ᴥ −)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (− ᴥ −)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (− ᴥ .)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (− ᴥ −)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "waiting".to_string(),
            name: "waiting".to_string(),
            color: EmotionColor::Neutral,
            ms: 700,
            frames: vec![
                "  ╭───╮\n ( ᴥ .  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ .. )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ ...)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ .. )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ .  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ    )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "searching".to_string(),
            name: "searching".to_string(),
            color: EmotionColor::Amber,
            ms: 400,
            frames: vec![
                "  ╭───╮\n (? ᴥ ? )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ?ᴥ ?)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (?ᴥ  ? )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (? ᴥ ? )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ ?? )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (??ᴥ   )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "onroll".to_string(),
            name: "on a roll".to_string(),
            color: EmotionColor::Green,
            ms: 180,
            frames: vec![
                "  ╭───╮\n ( ★ᴥ★ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ✦ᴥ✦ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ★ᴥ★ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ✦ᴥ✦ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ★ᴥ★ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ★ᴥ★ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "switching".to_string(),
            name: "context-switching".to_string(),
            color: EmotionColor::Amber,
            ms: 200,
            frames: vec![
                "  ╭───╮\n (←ᴥ→ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (→ᴥ← )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (←ᴥ→ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (→ᴥ← )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (↔ᴥ↔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (←ᴥ→ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "overwhelmed".to_string(),
            name: "overwhelmed".to_string(),
            color: EmotionColor::Coral,
            ms: 150,
            frames: vec![
                "  ╭───╮\n (ಠ ᴥ ಠ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ಠ ᴥ ಠ)\n  ╰─∪∪─╯".to_string(),
                " ╭────╮\n (ಠ ᴥ ಠ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ಠ ᴥ ಠ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ಠᴥ ಠ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ಠᴥಠ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ಠ ᴥ ಠ)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "happy".to_string(),
            name: "happy".to_string(),
            color: EmotionColor::Green,
            ms: 500,
            frames: vec![
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ^ᴥ^  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "content".to_string(),
            name: "content".to_string(),
            color: EmotionColor::Green,
            ms: 2500,
            frames: vec![
                "  ╭───╮\n ( ᵕᴥᵕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥᵕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥᵕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥᵕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥᵕ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "grumpy".to_string(),
            name: "grumpy".to_string(),
            color: EmotionColor::Coral,
            ms: 1400,
            frames: vec![
                "  ╭───╮\n ( `ᴥ´ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( `ᴥ´ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (  ᴥ´ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( `ᴥ´ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( `ᴥ  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( `ᴥ´ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( >ᴥ< )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( `ᴥ´ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "anxious".to_string(),
            name: "anxious".to_string(),
            color: EmotionColor::Coral,
            ms: 350,
            frames: vec![
                "  ╭───╮\n ( ᴖᴥᴖ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴖᴥᴖ )\n  ╰─∪∪─╯".to_string(),
                " ╭────╮\n ( ᴖᴥᴖ )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴖᴥᴖ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴖᴥᴖ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ᴖ ᴥ ᴖ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴖᴥᴖ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "panicked".to_string(),
            name: "panicked".to_string(),
            color: EmotionColor::Coral,
            ms: 80,
            frames: vec![
                "  ╭───╮\n (ﾟ ᴥ ﾟ)\n  ╰─∪∪─╯".to_string(),
                " ╭────╮\n (ﾟ ᴥ ﾟ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ﾟ ᴥ ﾟ)\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n (ﾟ ᴥ ﾟ)\n  ╰─∪∪─╯".to_string(),
                "╭─────╮\n (ﾟ ᴥ ﾟ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ﾟ ᴥ ﾟ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ﾟᴥ  ﾟ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ﾟ ᴥ ﾟ)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "relieved".to_string(),
            name: "relieved".to_string(),
            color: EmotionColor::Green,
            ms: 600,
            frames: vec![
                "  ╭───╮\n ( ᵒᴥᵒ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵒᴥᵒ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥᵕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵒᴥᵒ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵒᴥᵒ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵒᴥᵒ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "melancholy".to_string(),
            name: "melancholy".to_string(),
            color: EmotionColor::Violet,
            ms: 2800,
            frames: vec![
                "  ╭───╮\n ( ´ᴥ` )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ´ᴥ` )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ´ᴥ` )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ´ᴥ` )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ´ᴥ` )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( `ᴥ` )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ´ᴥ` )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "irritable".to_string(),
            name: "irritable".to_string(),
            color: EmotionColor::Coral,
            ms: 280,
            frames: vec![
                "  ╭───╮\n ( >ᴥ< )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( >ᴥ< )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (`>ᴥ<´)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( >ᴥ< )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( >ᴥ< )\n  ╰─∪∪─╯".to_string(),
                " ╭────╮\n ( >ᴥ< )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( >ᴥ< )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "calm".to_string(),
            name: "calm".to_string(),
            color: EmotionColor::Neutral,
            ms: 3200,
            frames: vec![
                "  ╭───╮\n ( ‿ᴥ‿ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ‿ᴥ‿ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ‿ᴥ‿ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ‿ᴥ‿ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥᵕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ‿ᴥ‿ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "restless".to_string(),
            name: "restless".to_string(),
            color: EmotionColor::Amber,
            ms: 400,
            frames: vec![
                "  ╭───╮\n (~ᴥ~  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ~ᴥ~ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (  ~ᴥ~)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ~ᴥ~ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (~ᴥ~  )\n  ╰─∪∪─╯".to_string(),
                " ╭────╮\n ( ~ᴥ~ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ~ᴥ~ )\n ╰──∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "uneasy".to_string(),
            name: "uneasy".to_string(),
            color: EmotionColor::Amber,
            ms: 700,
            frames: vec![
                "  ╭───╮\n ( ›ᴥ‹ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ›ᴥ‹ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (›ᴥ‹  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ›ᴥ‹ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (  ›ᴥ‹)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ›ᴥ‹ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴖᴥᴖ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ›ᴥ‹ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "proud".to_string(),
            name: "proud".to_string(),
            color: EmotionColor::Sky,
            ms: 1000,
            frames: vec![
                "  ╭───╮\n ( ᴑᴥᴑ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴑᴥᴑ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴑᴥᴑ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ᴑᴥᴑ  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴑᴥᴑ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ★ᴥ★ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴑᴥᴑ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "defeated".to_string(),
            name: "defeated".to_string(),
            color: EmotionColor::Coral,
            ms: 3800,
            frames: vec![
                "  ╭───╮\n ( xᴥx )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( xᴥx )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( xᴥx )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( xᴥx )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( xᴥx )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( _ᴥ_ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( xᴥx )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "lonely".to_string(),
            name: "lonely".to_string(),
            color: EmotionColor::Violet,
            ms: 2000,
            frames: vec![
                "  ╭───╮\n ( ╥ᴥ╥ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ╥ᴥ╥ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ╥ᴥ╥ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ╥ᴥ╥ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ╥ᴥ. )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ╥ᴥ╥ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( .ᴥ╥ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ╥ᴥ╥ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "sociable".to_string(),
            name: "sociable".to_string(),
            color: EmotionColor::Rose,
            ms: 450,
            frames: vec![
                "  ╭───╮\n ( ♥ᴥ♥ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ♥ᴥ♥ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ♥ᴥ♥  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ♥ᴥ♥ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ♥ᴥ♥ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◕ᴥ◕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ♥ᴥ♥ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "clingy".to_string(),
            name: "clingy".to_string(),
            color: EmotionColor::Rose,
            ms: 500,
            frames: vec![
                "  ╭───╮\n ( ᴗᴥᴗ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ᴗᴥᴗ  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴗᴥᴗ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴗᴥᴗ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ♥ᴥᴗ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴗᴥ♥ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴗᴥᴗ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "shy".to_string(),
            name: "shy".to_string(),
            color: EmotionColor::Neutral,
            ms: 1500,
            frames: vec![
                "  ╭───╮\n (/ ᴥ \\)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (/ ᴥ \\)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (/ ᴥ \\)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (/ ᴥ \\)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( /ᴥ\\ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (/ ᴥ \\)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (  ᴥ  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (/ ᴥ \\)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "warm".to_string(),
            name: "warm".to_string(),
            color: EmotionColor::Green,
            ms: 800,
            frames: vec![
                "  ╭───╮\n ( ◕ᴥ◕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◕ᴥ◕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◕ᴥ◕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◕ᴥ◕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ♥ᴥ◕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◕ᴥ◕ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "ignored".to_string(),
            name: "ignored".to_string(),
            color: EmotionColor::Violet,
            ms: 2600,
            frames: vec![
                "  ╭───╮\n ( ·ᴥ· )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ·ᴥ· )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ·ᴥ· )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ·ᴥ· )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (  ·ᴥ·)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ·ᴥ· )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ·ᴥ· )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "popular".to_string(),
            name: "popular".to_string(),
            color: EmotionColor::Rose,
            ms: 350,
            frames: vec![
                "  ╭───╮\n (♪ ᴥ ♪)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (♪ ᴥ ♫)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (♫ ᴥ ♪)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (♪ ᴥ ♪)\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n(♪ ᴥ ♪ )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n (♫ ᴥ ♫)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (♪ ᴥ ♪)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "isolated".to_string(),
            name: "isolated".to_string(),
            color: EmotionColor::Violet,
            ms: 3000,
            frames: vec![
                "  ╭───╮\n ( ╮ᴥ╭ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ╮ᴥ╭ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ╮ᴥ╭ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ╮ᴥ╭ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ╮ᴥ╭ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (  ᴥ   )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ╮ᴥ╭ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "curious".to_string(),
            name: "curious".to_string(),
            color: EmotionColor::Teal,
            ms: 500,
            frames: vec![
                "  ╭───╮\n ( oᴥo )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( oᴥo  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( oᴥo )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( Oᴥo )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( oᴥO )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( oᴥo )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◔ᴥ◔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( oᴥo )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "suspicious".to_string(),
            name: "suspicious".to_string(),
            color: EmotionColor::Amber,
            ms: 900,
            frames: vec![
                "  ╭───╮\n (¬ ᴥ ¬)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (¬ ᴥ ¬)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (¬ ᴥ  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (¬ ᴥ ¬)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (  ᴥ ¬)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (¬ ᴥ ¬)\n  ╰─∪∪─╯".to_string(),
                " ╭────╮\n (¬ ᴥ ¬)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (¬ ᴥ ¬)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "surprised".to_string(),
            name: "surprised".to_string(),
            color: EmotionColor::Coral,
            ms: 120,
            frames: vec![
                "  ╭───╮\n ( OwO )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( OwO )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n(  OwO )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( OwO )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( OwO )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( OwO )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵒᴥᵒ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( OwO )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "watchful".to_string(),
            name: "watchful".to_string(),
            color: EmotionColor::Sky,
            ms: 1600,
            frames: vec![
                "  ╭───╮\n ( ◉ᴥ◉ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◉ᴥ◉ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◉ᴥ◉ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ◉ᴥ◉  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ◉ᴥ◉ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ⊙ᴥ⊙ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◉ᴥ◉ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "confused".to_string(),
            name: "confused".to_string(),
            color: EmotionColor::Amber,
            ms: 600,
            frames: vec![
                "  ╭───╮\n ( ≍ᴥ≍ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (≍ ᴥ ≍)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ≍ᴥ≍ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ≍ᴥ≍  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ≍ᴥ≍ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ?ᴥ≍ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ≍ᴥ? )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ≍ᴥ≍ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "intrigued".to_string(),
            name: "intrigued".to_string(),
            color: EmotionColor::Teal,
            ms: 800,
            frames: vec![
                "  ╭───╮\n ( ◔ᴥ◔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◔ᴥ◔ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ◔ᴥ◔  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ◔ᴥ◔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◕ᴥ◔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◔ᴥ◕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ◔ᴥ◔ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "hot".to_string(),
            name: "hot".to_string(),
            color: EmotionColor::Coral,
            ms: 250,
            frames: vec![
                "  ╭~~~╮\n ( °ᴥ° )\n  ╰~∪∪~╯".to_string(),
                "  ╭~~~╮\n (°ᴥ°  )\n  ╰~∪∪~╯".to_string(),
                "  ╭~~~╮\n ( °ᴥ° )\n ╰~~∪∪~╯".to_string(),
                " ╭~~~~╮\n ( °ᴥ° )\n  ╰~∪∪~╯".to_string(),
                "  ╭~~~╮\n ( °ᴥ°)\n  ╰~∪∪~╯".to_string(),
                "  ╭~~~╮\n ( °ᴥ° )\n  ╰~∪∪~╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "sweating".to_string(),
            name: "sweating".to_string(),
            color: EmotionColor::Coral,
            ms: 200,
            frames: vec![
                "  ╭~~~╮\n (;°ᴥ°;)\n  ╰~∪∪~╯".to_string(),
                " ╭~~~~╮\n (;°ᴥ°;)\n  ╰~∪∪~╯".to_string(),
                "  ╭~~~╮\n (;°ᴥ°;)\n ╰~~∪∪~╯".to_string(),
                "  ╭~~~╮\n (;°ᴥ°;)\n  ╰~∪∪~╯".to_string(),
                "╭~~~~~╮\n (;°ᴥ°;)\n  ╰~∪∪~╯".to_string(),
                "  ╭~~~╮\n (;°ᴥ°;)\n  ╰~∪∪~╯".to_string(),
                "  ╭~~~╮\n (;ᴥ  ;)\n  ╰~∪∪~╯".to_string(),
                "  ╭~~~╮\n (;°ᴥ°;)\n  ╰~∪∪~╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "comfortable".to_string(),
            name: "comfortable".to_string(),
            color: EmotionColor::Green,
            ms: 2800,
            frames: vec![
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥᵕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "cramped".to_string(),
            name: "cramped".to_string(),
            color: EmotionColor::Amber,
            ms: 600,
            frames: vec![
                "  ╔═══╗\n ( ▓ᴥ▓ )\n  ╚═∪∪═╝".to_string(),
                "  ╔═══╗\n (▓ᴥ▓  )\n  ╚═∪∪═╝".to_string(),
                "  ╔═══╗\n ( ▓ᴥ▓ )\n  ╚═∪∪═╝".to_string(),
                "  ╔═══╗\n (  ▓ᴥ▓)\n  ╚═∪∪═╝".to_string(),
                "  ╔═══╗\n ( ▓ᴥ▓ )\n  ╚═∪∪═╝".to_string(),
                " ╔════╗\n ( ▓ᴥ▓ )\n  ╚═∪∪═╝".to_string(),
                "  ╔═══╗\n ( ▓ᴥ▓ )\n ╚══∪∪═╝".to_string(),
            ],
        },
        EmotionSpec {
            key: "airy".to_string(),
            name: "airy".to_string(),
            color: EmotionColor::Green,
            ms: 1400,
            frames: vec![
                "  ╭ · · ╮\n ( ᵕᴥᵕ )\n  ╰ · · ╯".to_string(),
                "  ╭ ·   ╮\n ( ᵕᴥᵕ )\n  ╰   · ╯".to_string(),
                "  ╭ · · ╮\n ( ᵕᴥᵕ )\n  ╰ · · ╯".to_string(),
                "  ╭ · · ╮\n ( ᵔᴥᵔ )\n  ╰ · · ╯".to_string(),
                "  ╭ · · ╮\n ( ᵕᴥᵕ )\n  ╰ · · ╯".to_string(),
                "  ╭ ·   ╮\n ( ᵕᴥᵕ )\n  ╰ ·   ╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "hungry".to_string(),
            name: "hungry".to_string(),
            color: EmotionColor::Amber,
            ms: 700,
            frames: vec![
                "  ╭───╮\n ( ᵒᴥᵒ )~\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵒᴥᵒ ) \n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵒᴥᵒ )~\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( oᴥo )~\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵒᴥᵒ )~\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵒᴥᵒ ) \n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( Oᴥo )~\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "stuffed".to_string(),
            name: "stuffed".to_string(),
            color: EmotionColor::Green,
            ms: 2200,
            frames: vec![
                "  ╭───╮\n ( ᴗᴥᴗ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴗᴥᴗ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴗᴥᴗ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥᵕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴗᴥᴗ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴗᴥᴗ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ- )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴗᴥᴗ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "cooped".to_string(),
            name: "cooped up".to_string(),
            color: EmotionColor::Violet,
            ms: 1100,
            frames: vec![
                "  ╔───╗\n ( =ᴥ= )\n  ╚─∪∪─╝".to_string(),
                "  ╔───╗\n (=ᴥ=  )\n  ╚─∪∪─╝".to_string(),
                "  ╔───╗\n ( =ᴥ= )\n  ╚─∪∪─╝".to_string(),
                "  ╔───╗\n (  =ᴥ=)\n  ╚─∪∪─╝".to_string(),
                "  ╔───╗\n ( =ᴥ= )\n  ╚─∪∪─╝".to_string(),
                " ╔────╗\n ( =ᴥ= )\n  ╚─∪∪─╝".to_string(),
                "  ╔───╗\n ( =ᴥ= )\n ╚──∪∪─╝".to_string(),
            ],
        },
        EmotionSpec {
            key: "excited".to_string(),
            name: "excited".to_string(),
            color: EmotionColor::Green,
            ms: 200,
            frames: vec![
                "  ╭───╮\n ( ✦ᴥ✦ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ✦ᴥ✦  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ✦ᴥ✦ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ✦ᴥ✦ )\n  ╰─∪∪─╯".to_string(),
                "╭──────╮\n( ✦ᴥ✦  )\n╰───∪∪─╯".to_string(),
                "  ╭───╮\n ( ✦ᴥ✦ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "settled".to_string(),
            name: "settled".to_string(),
            color: EmotionColor::Green,
            ms: 3000,
            frames: vec![
                "  ╭───╮\n ( ᵔ ᴥ ᵔ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔ ᴥ ᵔ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔ ᴥ ᵔ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔ ᴥ ᵔ)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥᵕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔ ᴥ ᵔ)\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "onedge".to_string(),
            name: "on edge".to_string(),
            color: EmotionColor::Amber,
            ms: 320,
            frames: vec![
                "  ╭───╮\n (! ᴥ ! )\n  ╰─∪∪─╯".to_string(),
                " ╭────╮\n (! ᴥ ! )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (! ᴥ ! )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (!ᴥ  ! )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (! ᴥ ! )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n (! ᴥ ! )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ᴖ ᴥ ᴖ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (! ᴥ ! )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "nostalgic".to_string(),
            name: "nostalgic".to_string(),
            color: EmotionColor::Neutral,
            ms: 2200,
            frames: vec![
                "  ╭───╮\n ( ~ᴥ~ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ~ᴥ~ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ~ᴥ~ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ˘ᴥ˘ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ~ᴥ~ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ~ᴥ~ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ´ᴥ` )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ~ᴥ~ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "adventurous".to_string(),
            name: "adventurous".to_string(),
            color: EmotionColor::Teal,
            ms: 500,
            frames: vec![
                "  ╭───╮\n ( →ᴥ→ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( →ᴥ→  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( →ᴥ→ )\n  ╰─∪∪─╯".to_string(),
                "   ╭───╮\n  ( →ᴥ→ )\n   ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( →ᴥ→ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( oᴥ→ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( →ᴥ→ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "jetlagged".to_string(),
            name: "jet-lagged".to_string(),
            color: EmotionColor::Amber,
            ms: 900,
            frames: vec![
                "  ╭───╮\n ( %ᴥ% )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( %ᴥ% )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( %ᴥ%〃)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( %ᴥ% )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (%ᴥ%  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( %ᴥ%〃)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( %ᴥ% )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( _ ᴥ _)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( %ᴥ% )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "nightowl".to_string(),
            name: "night-owl".to_string(),
            color: EmotionColor::Violet,
            ms: 1200,
            frames: vec![
                "  ╭───╮\n ( ☽ᴥ☽ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ☽ᴥ☽ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ☽ᴥ☽ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (ò ᴥ ó)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ☽ᴥ☽ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ☽ᴥ☽ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ-〃)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ☽ᴥ☽ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "morning".to_string(),
            name: "morning person".to_string(),
            color: EmotionColor::Green,
            ms: 800,
            frames: vec![
                "  ╭───╮\n ( ☀ᴥ☀ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ☀ᴥ☀  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ☀ᴥ☀ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ☀ᴥ☀ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ☀ᴥ☀ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "secretive".to_string(),
            name: "secretive".to_string(),
            color: EmotionColor::Amber,
            ms: 1800,
            frames: vec![
                "  ╭───╮\n ( ‹ᴥ› )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ‹ᴥ› )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ‹ᴥ› )\n  ╰─∪∪─╯".to_string(),
                " ╭────╮\n ( ‹ᴥ› )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ‹ᴥ› )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (  ᴥ  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ‹ᴥ› )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "performative".to_string(),
            name: "performative".to_string(),
            color: EmotionColor::Rose,
            ms: 400,
            frames: vec![
                "  ╭───╮\n ( ▶ᴥ◀ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ▶ᴥ◀  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ▶ᴥ◀ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ★ᴥ★ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ▶ᴥ◀ )\n  ╰─∪∪─╯".to_string(),
                "╭──────╮\n( ▶ᴥ◀  )\n╰───∪∪─╯".to_string(),
                "  ╭───╮\n ( ▶ᴥ◀ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "productive".to_string(),
            name: "productive".to_string(),
            color: EmotionColor::Sky,
            ms: 700,
            frames: vec![
                "  ╭───╮\n ( ᴧᴥᴧ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴧᴥᴧ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ᴧᴥᴧ  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴧᴥᴧ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (・ᴥ・ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴧᴥᴧ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "burnedout".to_string(),
            name: "burned out".to_string(),
            color: EmotionColor::Coral,
            ms: 4000,
            frames: vec![
                "  ╭───╮\n ( _ᴥ_ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( _ᴥ_ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( _ᴥ_ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( _ᴥ_ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( _ᴥ_ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( xᴥ_ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( _ᴥ_ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "wakingup".to_string(),
            name: "waking up".to_string(),
            color: EmotionColor::Green,
            ms: 800,
            frames: vec![
                "  ╭───╮\n ( _ ᴥ _)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( _ ᴥ _)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ˘ᴥ_ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ˘ᴥ˘ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ˘ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "windingdown".to_string(),
            name: "winding down".to_string(),
            color: EmotionColor::Amber,
            ms: 1500,
            frames: vec![
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥᵕ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵕᴥ- )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ- )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ-〃)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ- )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ˘ᴥ˘ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "zoningout".to_string(),
            name: "zoning out".to_string(),
            color: EmotionColor::Neutral,
            ms: 2000,
            frames: vec![
                "  ╭───╮\n ( ∙ᴥ∙ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ∙ᴥ∙ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ∙ᴥ∙ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ∙ᴥ∙ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (∙ ᴥ ∙)\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ∙ᴥ∙ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ∙ᴥ. )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ∙ᴥ∙ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "snappingback".to_string(),
            name: "snapping back".to_string(),
            color: EmotionColor::Sky,
            ms: 100,
            frames: vec![
                "  ╭───╮\n ( !ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( OwO )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( !ᴥ^  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( !ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n (・ᴥ・ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( !ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "packingup".to_string(),
            name: "packing up".to_string(),
            color: EmotionColor::Neutral,
            ms: 1000,
            frames: vec![
                "  ╭───╮\n ( ᴥ ›› )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ ›  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ ›› )\n  ╰─∪∪─╯".to_string(),
                "   ╭───╮\n  ( ᴥ ›› )\n   ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ ›› )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( -ᴥ ›  )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᴥ ›› )\n  ╰─∪∪─╯".to_string(),
            ],
        },
        EmotionSpec {
            key: "startingfresh".to_string(),
            name: "starting fresh".to_string(),
            color: EmotionColor::Green,
            ms: 600,
            frames: vec![
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                " ╭─────╮\n( ᵔᴥᵔ  )\n ╰──∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ^ᴥ^ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ✦ᴥ✦ )\n  ╰─∪∪─╯".to_string(),
                "  ╭───╮\n ( ᵔᴥᵔ )\n  ╰─∪∪─╯".to_string(),
            ],
        },
    ]
}
